/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./duck.gltf
Author: Xabier Garcia (https://sketchfab.com/XabS11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoony-rubber-ducky-8a6e661916b74f9caa1c20dd6fdf77ad
Title: Cartoony Rubber Ducky
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export function DuckModel({ mousePosition }: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/duck.gltf');

  const modelRef = React.useRef<any>();

  useFrame((state: any) => {
    const model = modelRef.current;
    if (mousePosition && model) {
      model.position.y = model.position.y + Math.sin(state.clock.getElapsedTime() * 2) * 0.005;
      model.rotation.x = (mousePosition.y - window.innerHeight / 2) / 2000 + 0.1;
      model.rotation.y = (mousePosition.x - window.innerWidth / 2) / 2000 + 0.12;
    }
    // console.log(mousePosition);
  });
  return (
    <group ref={modelRef} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.lambert2SG}
        position={[0, -1.6, 0]}
        rotation={[-Math.PI / 2, 0, 3.8]}
        scale={0.4}
      />
    </group>
  );
}

useGLTF.preload('/duck.gltf');
